services:

  ghost:
    container_name: jg_blog
    image: ghost:5-alpine
    restart: always
    ports:
      - 7000:2368
    env_file:
      - .env
    environment:
      # see https://ghost.org/docs/config/#configuration-options
      database__client: mysql
      database__connection__host: db
      database__connection__user: ${DB_USER} # must = root
      database__connection__password: ${DB_PASSWORD}
      database__connection__database: ${DB_NAME} # must = ghost
      url: ${GHOST_URL}
      #NODE_ENV: development
    volumes:
      - ghost:/var/lib/ghost/content
      # - ./custom/RubyJG:/var/lib/ghost/content/themes/RubyJG # for custom theme

  db:
    container_name: blog_db
    image: mysql:8.0
    restart: always
    env_file:
      - .env
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
    volumes:
      - db:/var/lib/mysql

volumes:
  ghost:
  db:
